# Generated by Django 4.2.7 on 2024-01-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_ag', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ag', models.CharField(max_length=50)),
                ('apellido_ag', models.CharField(max_length=50)),
                ('numero_ag', models.IntegerField()),
                ('email_ag', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_ag', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ag', models.DateField()),
                ('hora_ag', models.TimeField()),
                ('total_ag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas_cliente', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ag', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ag', models.CharField(max_length=50)),
                ('marca_ag', models.CharField(max_length=100)),
                ('stock_ag', models.IntegerField()),
                ('fecha_ven_ag', models.DateField()),
                ('indicacion_ag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_ag', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_ag', models.TextField()),
                ('cantidad_ag', models.IntegerField()),
                ('metodo_pago_ag', models.CharField(max_length=50)),
                ('codigo_ag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id_ag', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ag', models.CharField(max_length=80)),
                ('descripcion_ag', models.TextField()),
                ('precio_ag', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fotografia_ag', models.FileField(blank=True, null=True, upload_to='platillos')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_ag', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ag', models.CharField(max_length=50)),
                ('codigo_ag', models.IntegerField()),
                ('capital_ag', models.CharField(max_length=50)),
                ('idioma_ag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_ag', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ag', models.CharField(max_length=100)),
                ('instrucciones_ag', models.TextField()),
                ('tiempo_preparacion_ag', models.TimeField()),
                ('fecha_creacion_ag', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_ag', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ag', models.CharField(max_length=50)),
                ('categoria_ag', models.CharField(max_length=100)),
                ('descripcion_ag', models.TextField()),
            ],
        ),
    ]
